version: '3.9'

x-base_service: &base_service
    ports:
      - "${WEBUI_PORT:-9101}:7860"
      #- "${WEBUI_PORT:-7860}:7860"
    volumes:
      - &v1 ./data:/data
      - &v2 ./output:/output
      - &v3 /mnt/data:/mnt/data
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]

name: webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - *v1

  auto: &automatic
    <<: *base_service
    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    image: sd-linky:68
    environment:
      - CLI_ARGS=--allow-code --xformers --enable-insecure-extension-access --api

